apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-service-config
data:
  SPRING_APPLICATION_NAME: hello-service
  SERVER_PORT: "8080"
  GREETING_MESSAGE: "Hello from hello-service!"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always" 